ALTER TABLE accounts
DROP
CONSTRAINT accounts_role_id_fkey;

ALTER TABLE event_participants
DROP
CONSTRAINT event_participants_event_id_fkey;

ALTER TABLE events
DROP
CONSTRAINT events_sport_id_fkey;

ALTER TABLE games
DROP
CONSTRAINT games_created_by_fkey;

ALTER TABLE games
DROP
CONSTRAINT games_last_updated_by_fkey;

ALTER TABLE games
DROP
CONSTRAINT games_sport_id_fkey;

ALTER TABLE league_participants
DROP
CONSTRAINT league_participants_league_id_fkey;

ALTER TABLE matches
DROP
CONSTRAINT matches_season_id_fkey;

ALTER TABLE matches
DROP
CONSTRAINT matches_session_id_fkey;

ALTER TABLE rules
DROP
CONSTRAINT rules_sport_id_fkey;

ALTER TABLE seasons
DROP
CONSTRAINT seasons_sport_id_fkey;

ALTER TABLE session_participants
DROP
CONSTRAINT session_participants_session_id_fkey;

ALTER TABLE sessions
DROP
CONSTRAINT sessions_sport_id_fkey;

ALTER TABLE team_matches
DROP
CONSTRAINT team_matches_team_one_id_fkey;

ALTER TABLE team_matches
DROP
CONSTRAINT team_matches_team_two_id_fkey;

ALTER TABLE team_matches
DROP
CONSTRAINT team_matches_winner_team_id_fkey;

ALTER TABLE team_members
DROP
CONSTRAINT team_members_team_id_fkey;

ALTER TABLE accounts
DROP
COLUMN role_id;

ALTER TABLE matches
DROP
COLUMN season_id;

ALTER TABLE matches
DROP
COLUMN session_id;

ALTER TABLE events
DROP
COLUMN sport_id;

ALTER TABLE rules
DROP
COLUMN sport_id;

ALTER TABLE seasons
DROP
COLUMN sport_id;

ALTER TABLE sessions
DROP
COLUMN sport_id;

ALTER TABLE team_matches
DROP
COLUMN team_one_id;

ALTER TABLE team_matches
DROP
COLUMN team_two_id;

ALTER TABLE team_matches
DROP
COLUMN winner_team_id;

ALTER TABLE games
DROP
COLUMN created_by;

ALTER TABLE games
DROP
COLUMN id;

ALTER TABLE games
DROP
COLUMN last_updated_by;

ALTER TABLE games
    ADD created_by VARCHAR(255);

ALTER TABLE games
ALTER
COLUMN description TYPE VARCHAR(255) USING (description::VARCHAR(255));

ALTER TABLE games
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE games
    ADD last_updated_by VARCHAR(255);